---
title: "Diagrammes TikZ Quantiques"
author: Stéphane Caporali
date: "2025-08-29"
bibliography: fichier.bib
editor: source

format:
  pdf:
# Ceci est la ligne qui résout votre problème : le PDF sera généré
# au même niveau que le .qmd
    output-file: "code_tikz.pdf"

# Configuration de l'ingénieur de rendu
pdf-engine: xelatex

# Options de la table des matières et de la numérotation
toc: true
number-sections: true

# Inclusions de packages LaTeX (header-includes doit être ici)
header-includes:  
  - \usepackage{tikz}
  - \usepackage{pgfplots}
  - \usepackage{amsmath}
  - \usepackage{relsize}
  - \usepackage{exscale} # Inutile de répéter relsize,exscale
  - \usepackage[straightvoltages]{circuitikz}
  - \usepackage{braket}
  - \usepackage{mathtools}
---

# 1.Introduction :

## 1.1 Explication de la démarche pédagogique :



\usetikzlibrary{arrows}
\begin{figure}
\centering
    
 
\begin{tikzpicture}[scale=0.5]
  \fill [fill=black!40, draw=black, very thick, semitransparent]  
  (0,0) 
    -- (10,0) 
    -- (10,5.5) 
    -- (9,5.5) 
    -- (9,1)
    -- (1,1)
    -- (1,11)
    -- (9,11)
    -- (9,6.5)
    -- (10,6.5)
    -- (10,12)
    -- (0,12) ;
 \draw[->, magenta,line width=2pt] (12,7) -- (1,3.5) -- (4,11) -- (9,8) [dashed, blue] node[left, purple] {\begin{tabular}{c}L’énergie électromagnétique (lumière) \\ est piégée par le corps noir\end{tabular}};

 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] (10,2) -- (12,2);
 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] (10,4) -- (12,4);
 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] (10,8) -- (12,8);
 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] (10,10) -- (12,10);

\draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] (0,2) -- (-2,2);
 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] (0,4) -- (-2,4);
 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] (0,8) -- (-2,8);
 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] (0,10) -- (-2,10);

\draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] (1,12) -- (1,14);
 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] 
 (3,12) -- (3,14);
 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] (5,12) -- (5,14);
 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] (7,12) -- (7,14);

 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] (1,12) -- (1,14);
 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] 
 (3,12) -- (3,14);
 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] (5,12) -- (5,14);
 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] (7,12) -- (7,14);

 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] (1,0) -- (1,-2);
 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] 
 (3,0) -- (3,-2);
 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] (5,0) -- (5,-2);
 \draw [arrows = {-Latex[width=7pt, length=7pt]},dashed, blue,line width=1pt] (7,0) -- (7,-2);
 \draw (5,-3) node [purple] {\begin{tabular}{c}L’énergie est ensuite restituée \\ sous forme de rayonnement thermique\end{tabular}};

       
\end{tikzpicture}
       
 
\caption{Certains objets, comme l'intérieur d'un four chauffé uniformément, peuvent approcher le modèle du corps noir.}
\end{figure}
 

\usetikzlibrary {arrows.meta}
\usetikzlibrary {decorations.pathmorphing}
\begin{figure} 
\centering
 
     
 \begin{tikzpicture}[scale=0.5]

 %   \tikzset{shift={(current page.center)},yshift=-1.5cm}
  
  \foreach \x in {-5,-4,-3,-2,-1,-2,0,1,2,3}
    \foreach \y in {-1,0,1,2,3}
      {
        \draw [fill=red] (\x,\y) circle (0.3cm);
      %  \fill (\x,\y) circle (0.1cm);
      }

 %   \draw[decorate,decoration={snake,segment length=2cm},->] (0,0) - - (10,0);
    \draw[decorate,decoration=snake,magenta,-{Stealth[length=5mm]}] (-5,7) - - (-1,3.2) ;
    \draw[decorate,decoration=snake,magenta,-{Stealth[length=5mm]}] (-6,7) - - (-2,3.2) ;
    \draw[decorate,decoration=snake,magenta,-{Stealth[length=5mm]}] (-7,7) - - (-3,3.2) ;

    
    \draw [fill=blue] (2,5) circle (0.3cm);
    \draw[blue,-{Stealth[length=5mm]}] (2,5) -- (3,8);

     \draw [fill=blue] (0,4) circle (0.3cm);
    \draw[blue,-{Stealth[length=5mm]}] (0,4) -- (1,6);
    
   % \draw[decorate,decoration=snake ] (0,0) arc (0:180:3 and 2);

   
   
\end{tikzpicture}

\caption{ L'énergie reçue par le rayonnement électromagnétique va permettre à des électrons de s'éjecter du matériau. On observe une corrélation entre l'énergie reçue (quantifiée) et celle de l'électron}
\end{figure}

 
 

\begin{figure}
\centering
\begin{tikzpicture}
 \draw (0,0) node (a) {};
\draw (1,3) [label=lettre2] node (b) {$P_2$};
\draw[->] (a) -- (b);
\draw (3,1) [label=lettre2] node (e) {$P_1$};
\draw[->] (a) -- (e);
\draw [->,purple] (1,0.35) arc (30:49:3) node[right,pos=0.6] {\tiny{$\alpha$}};
  \draw[->] (-1,0) -- (5,0) node[right] {$x$};  
  \draw[->] (0,-1.5) -- (0,3.5) node[above] {$y$}; 

\end{tikzpicture}
\end{figure}

 

### 3.1.3 Homothétie :

 

\begin{figure}
\centering
\begin{tikzpicture}
\draw (0,0) node (a) {};
\draw (3,1.5) [label=lettre2] node (b) {$P_2$};
\draw[->] (a) -- (b);
\draw (1,0.5) [label=lettre2] node (e) {$P_1$};
\draw[->,red] (a) -- (e);
\draw[->] (-1,0) -- (5,0) node[right] {$x$}; % Axe horizontal
\draw[->] (0,-1.5) -- (0,3.5) node[above] {$y$}; % Axe vertical
\end{tikzpicture}
\end{figure}

 
 
 
 

## 3.14 Représentation d'un opérateur sur la base des vecteurs propres d'une matrice hermitique :

 

\begin{figure}
\centering
\begin{tikzpicture}
\draw (0,0) [label=lettre1] node (a) {};
\draw (1,3) [label=lettre2] node (b) {$B\ket{V}=x_1B\ket{V_1} + x_2B\ket{V_2}$};
\draw[->] (a) -- (b);
\draw (3,2) [label=lettre2] node (e) {$\ket{V}=x_1\ket{V_1} + x_2\ket{V_2}$};
\draw[dashed, ->] (a) -- (e);
\draw[->] (-1,0) -- (5,0) node[right] {$x$}; 
\draw[->] (0,-1.5) -- (0,3.5) node[above] {$y$}; 
\end{tikzpicture}
\end{figure}

 
  

## 3.20 Conditions aux limites :

 

\begin{figure}
    
\begin{tikzpicture}[scale=1]
  % Tracé de la courbe sinusoïdale
  \draw[thick, domain=0:4*pi, samples=100] plot (\x, {sin(\x r)});

  % Axe horizontal
  \draw[->] (0,0) -- (4*pi + 0.5, 0) node[right] {$x$};

  % Axe vertical
  \draw[->] (0,-1.5) -- (0,1.5) node[above] {$A(x)$};

  % Indication de la période
  \draw[<->, thick] (0, -1.8) -- (2*pi, -1.8) node[midway, below, red] {$T$};

  % Marquage de la période
  \node at (pi, -1.5) {$\pi$};
  \node at (2*pi, -1.5) {$2\pi$};

  % Points clés pour la période
  \fill[blue] (0,0) circle (3pt);
  \node[above, red] at (0,0.5) {Limite inferieure};
  \fill[blue] (2*pi,0) circle (3pt) ; 
  \node[above, red] at (2*pi,0.5) {Limite supérieure};
  \fill (4*pi,0) circle (1pt);
\end{tikzpicture}
\caption{l'application des conditions au limites donne $A(0)=0$ et $A(2\pi)=0$}
 
\end{figure} 

 

 

## 4.2 Fentes d'Young avec des électrons :

\begin{tikzpicture}
\draw[->] (1,0) -- (3,0);
\draw[->] (3,0) -- (8,0);
\draw (1,0) node[scale=1.2]{$\bullet$} node [left]{$S$};
\draw[{-]}, blue] (3,2) -- (3,4) node[above]{};
\node [red] (A) at (3,1.5) {$S_1$};
\node [red] (B) at (3,-1.5) {$S_2$};
%\node [red] (C) at (3,-5) {Trous d'Young};
\node [red] (D) at (3,4.5) {Feuille de cuivre};
\node [red] (E) at (10,-3) {\begin{tabular}{l}Plan d'observation \\ ou de détection \end{tabular}};
\draw[{-]}, blue] (3,1) -- (3,-1);
\draw[{-]}, blue] (3,-4) -- (3,-2);
\draw[{-]}, red] (8,3) -- (8,-3);
\draw[dashed, <->] (3,-3) -- node[above]{$d$} (8,-3) ;
\draw[dashed, <->] (2,-2) -- node[above, right]{$a$} (2,-4) ;
\draw[->, magenta] (1,0) -- (3,2);
\draw[->, magenta] (1,0) -- (3,1);
\draw[->, magenta] (1,0) -- (3,-1);
\draw[->, magenta] (1,0) -- (3,-2);
%realisation des franges d'interference
\foreach \x in {0,0.1,...,0.8}
{
\draw [magenta] (7.8,\x) -- (8.2,\x+0.2); 
}
\foreach \x in {0,-0.1,...,-0.8}
{
\draw [magenta] (7.8,\x) -- (8.2,\x+0.2); 
}
\node [magenta] (F) at (10,0) {Franges d'interférence};

\end{tikzpicture}

 
 

    
## 6.7 Cas limites du principe d'incertitude :

 

\begin{center}
\begin{tikzpicture}[x=3.8cm/360]
  \pgfplothandlerlineto
\pgfplotfunction{\x}{-200,-199,...,0}{\pgfpointxy{\x}{0}}
\pgfplotfunction{\x}{0,1,...,792}{\pgfpointxy{\x}{sin(5*\x)}}
 
\pgfplotfunction{\x}{793,794,...,900}{\pgfpointxy{\x}{0}}
  \pgfusepath{stroke}
\draw (4.5cm,1.5cm)  node [fill=green!20] {La bande est large, l'incertitude sur $\Delta x$ est élevée};
\end{tikzpicture}
\end{center}

 

\begin{center}
 \begin{tikzpicture}[x=3.8cm/360]
  \pgfplothandlerlineto
  \pgfplotfunction{\x}{0,5,...,360}{\pgfpointxy{\x}{sin(\x)+sin(3*\x)}}
  \pgfusepath{stroke}
  \draw (4.5cm,2cm)  node [fill=green!20] {Ici difficile de dire si l'incertitude porte sur $\Delta x$ ou $\Delta p$};
\end{tikzpicture}
\end{center}
 
\begin{figure}
\centering
\begin{tikzpicture}
  % Définir la largeur epsilon
 % \def\epsilon{0.2}
  
  % Tracer l'axe horizontal
  \draw[->] (0,0) -- (2,0) node[right, blue] {$x$};
  \draw[->] (0,-0.2) -- (0,1.7) node[above, blue] {$f(x)=\delta^{\epsilon}(x-x_{0})$};
  
  % Tracer la fonction créneau
  \draw[thick, blue] 
    (1,0) -- (1,1) -- (1.3,1) -- (1.3,0);
  
  % Optionnel : ajouter des points ou des annotations
  \fill (0,1) circle (1pt);
  \fill (1.15,0) circle (1pt) node[below, red] {$x_{0}$} -- (1,1);
%  \fill (0.5+\epsilon,1) circle (1pt);
%  \fill (1,0) circle (1pt);

\draw[dashed] (0,1) node[left, red] {\Large $\frac{1}{\epsilon}$} -- (1,1) ;
  
  % Ajouter des labels
 \node at (0, 1) {$\frac{1}{\epsilon}$};

 \draw[<->,line width=0.5pt] (1,1.2) node[above, red] {\Large $\epsilon$} -- (1.3,1.2) ;

\end{tikzpicture}
\end{figure}
 

## 6.13 Utilité de la fonction porte :

 

\begin{figure}
\centering
  \begin{tikzpicture}[scale=0.8]
  \begin{axis}[
    domain=-10:10,
    samples=200,
    axis lines=middle,
    xlabel=$k$,
    ylabel=$g(k)$,
    xtick={-10,-8,...,10},
    ytick={-0.5,0,0.5,1},
    height=8cm,
    width=12cm,
    grid=both,
    clip=false
  ]
    \addplot [blue, thick] {sin(deg(x))/x};
    \addplot [mark=*, only marks] coordinates {(0,1)};
  \end{axis}
\end{tikzpicture}
\caption{La fonction sinus cardinal qui est la TF de la fonction porte ici prise en exemple sur l'intervel [-10,10]}
\end{figure}

  
 
 

## 7.2 Exemple tiré des télécommunications :

 

\begin{center}
\begin{circuitikz}
    \draw (0,0) to [short] ++(0,1) node [right] {$-$}
    to [open, v^>=$E(t)$, o-o] ++(0,1) node [right] {$+$}
    to [short] ++(0,1)
    to [R=$R$, i>^=$I$, resistors/zigs=6] ++(4,0)
    to [curved capacitor, l_=$C$, capacitors/thickness=8] ++(0,-3)
    to [cute inductor, l_=$L$, mirror] ++(-4,0);
\end{circuitikz}
\end{center}

   
 
\usetikzlibrary {arrows.meta}
\begin{figure}
\centering
\begin{tikzpicture}
 
 \node (A) at (0,0) {\begin{tabular}{c} Source $|\Psi\rangle=$ \\ $\Large{\sum}_{i,j\in I_{A} \times I_{B}}^{} a_{ij} |\phi^{A}_{i}\rangle \otimes |\phi^{B}_{j}\rangle $ \end{tabular}};
 \node (B) at (-5,5) {\begin{tabular}{c} Alice recoit : \\ $ |\psi(A|j)\rangle$ \end{tabular}};
 \node (C) at (5,5) {\begin{tabular}{c} Bob mesure : \\ $ j \Rightarrow |\phi_{j}^{B}\rangle$ \end{tabular}};
    \draw[-{Stealth[red]},line width=1mm,blue] (A) -- (C) node[midway,sloped,above] {$|?^B\rangle$};
     \draw[-{Stealth[red]},line width=1mm,blue] (A) -- (B) node[midway,sloped,above] {$|?^A\rangle$};
      \draw[-{Stealth[red]}, dotted,line width=1mm,blue] (C) -- (B) node[midway,sloped,above] {Projection de l'état global};
\end{tikzpicture}
\caption{Une source émet un état intriqué de deux systèmes dont l'un est envoyé à Alice et l'autre a Bob. Si on considère les expériences dans lesquelles bob effectue une mesure et qu'il trouve le résultat correspondant à l'état $|\phi_{j}^B\rangle$ alors le système d'Alice est dans l'état relatif $|\psi(A|j)\rangle$.}
\end{figure}

 

  
# Exercices :
 

## 6.9 Exercice 2 : interprétation de la diffraction avec le principe d'incertitude d'Heisenberg :

 

\begin{center}
\begin{tikzpicture}
    \draw[black,line width=5pt] (1,-0.5) -- (1,1);
     \draw[black,line width=5pt] (1,-1.5) -- (1,-3);
      \draw[<->, red] (0,-1.5) -- (0,-0.5);
      \node [magenta] (F) at (-0.3,-1) {\large{$a$}};
      \draw[->, black] (0,-1) -- (1,-1);
      \draw[->, black, dotted] (1,-1) -- (10,-1);
      \draw[->, black, dotted] (1,-1) -- (10,1);
       \draw[->, black, dotted] (1,-1) -- (10,-3);
       \draw[<->, black,line width=2pt] (10,-3) -- (10,1) node[right,pos=0.6] {\large{$L$}};;
       \draw[<->, blue] (1,-3.2) -- (10,-3.2) node[above,pos=0.6] {\large{$D$}};
  %    \draw (0,-1) grid  [step=1] (8,5);
  \draw [->,purple] (5,-1) arc (0:27:1.8) node[right,pos=0.6] {\large{$\theta$}};
\end{tikzpicture}
\end{center}

 

\begin{center}
\begin{tikzpicture}

 \draw[black, dashed] (1,0) -- (8,0);
 \draw[->, black, dashed] (1,0) -- (8,5);
 \draw [->,purple] (4,0) arc (0:40:2.5) node[right,pos=0.6] {\large{$\theta$}};
  \draw[->,red] (3,1.4) -- (3,4) node[right=0.18cm,pos=0.6] {\large{$\vec{p_{x}}$}};;;
  \draw[->,red] (3,1.4) -- (6.5,4) node[right=0.3cm,pos=0.6] {\large{$\vec{p}$}};;;
  \draw[->,red, dotted] (3,4) -- (6.5,4) ;
    
\end{tikzpicture}
\end{center}

 
  

\begin{figure}
\centering
 \begin{tikzpicture}
  \draw[->]  (-2,0) node {} -- (2,0)  node[right] {$x$};;
  \draw[->]  (0,0) node {} -- (0,3)  node[above] {$f(x)$};
  \draw[blue, line width=0.04cm]  (-1,0) node[below] {-a/2} -- (-1,2)  node[below left] {$1/a$};
  \draw[blue, line width=0.04cm]  (1,0) node[below] {a/2} -- (1,2)  node[below] {};
   \draw[blue, line width=0.04cm]  (-1,2) node[below] {} -- (1,2)  node[below] {};
\end{tikzpicture}
\end{figure}

 

 
 

## 6.17 Exercice 5 : paquet d'onde Gaussien :

 

\begin{center}
\begin{tikzpicture}
  \begin{axis}[
    domain=-4:4,
    samples=100,
    axis lines=middle,
    xlabel=$x$,
    ylabel={\textcolor{red}{$|\Phi_{max}|^2$}},
    height=6cm,
    width=10cm,
    title={Variation de la densité de probabilité $|\Phi_{max}|^2$}
  ]
    \addplot [
      thick,
      blue
    ] {1/sqrt(2*pi) * exp(-x^2/2)};
  \end{axis}
\end{tikzpicture}
\end{center}
 

## 8.1 Exercice 6 : le puits de potentiel infini

 

On considère un problème à une dimension correspondant à une particule de masse m et d'énergie E, placée dans un puit de potentiel infini de largeur a :

$$V(x)= \left\{
    \begin{array}{ll}
        0 & \mbox{si } -a \leq x \leq 0 \\
        +\infty & \mbox{ailleurs}
    \end{array}
\right.$$

\usetikzlibrary{patterns}
\begin{figure}
\centering
 \begin{tikzpicture}
  \draw[->]  (-3,0) node {} -- (3,0)  node[right] {$x$};;
  \draw[->]  (1,0) node {} -- (1,3)  node[above] {$V(x)$};
  \draw[blue, line width=0.04cm]  (-1,0) node[below] {-a} -- (-1,2.5)  node[left] {};
  \draw[blue, line width=0.04cm]  (1,0) node[below] {0} -- (1,2.5)  node[below] {};
%   \draw[blue, line width=0.04cm]  (-1,2) node[below] {} -- (1,2)  node[below] {};
 \fill[pattern=horizontal lines, pattern color=gray!50] (-1,0) rectangle (-3,3);
  \fill[pattern=horizontal lines, pattern color=gray!50] (1,0) rectangle (3,3);
   \node[red] at (-2,1.5) {(I)};
    \node[red] at (0,1.5) {(II)};
     \node[red] at (2,1.5) {(III)};
\end{tikzpicture}
\end{figure}

 
# Références :
